version: "3.9" # optional since v1.27.0

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/app
    environment:
      DATABASE_URI: postgresql://admin:password@postgres/dblinks
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: dblinks
